version: "3.7"
services:

  proxy:
    build:
      context: ./web/proxy
    command: ["./wait-for-it.sh", "--timeout=0", "webapp:3003", "--", "nginx", "-g", "daemon off;"]
    depends_on:
      - webapp
    restart: "no"
    entrypoint: ["echo", "Service proxy disabled"]

  webapp:
    build: web
    environment:
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
      RSA_PUBLIC_KEY: ${RSA_PUBLIC_KEY}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: unless-stopped
    volumes:
      - pf_uploads:/home/node/uploads
    depends_on:
      - mariadb
      - generator

  mariadb:
    build: web/db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - pf_data:/var/lib/mysql
    restart: unless-stopped

  migration:
    image: phenoflow_webapp:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["./bin/wait-for-it.sh", "--timeout=0", "phenoflow_mariadb_1:3306", "--", "npm", "run", "migrate"]
    depends_on:
      - mariadb
      - webapp

  generator:
    build:
      context: generator/
    restart: unless-stopped
    environment:
      PORT: 3004

volumes:
  pf_uploads:
  pf_data:

networks:
  default:
    external:
      name: hi_default # For proxy.
